### ISSUE TITLE
Multi-position switch

### ISSUE THREAD

**Issue by mrstacey1284** [Colorado4Wheeler/Device-Extensions#1]
I have a few instances where I need a multi-positional switch, such as the TV switch. I would like a switch that can select between Off, Apple TV, or Live TV. Or an Alarm Switch that offers Off, Armed Home, Armed Away, and Triggered state. I used the wrapper feature in Homebridge Buddy before switching to Homekit Buddy and was hoping Device Extensions would offer a similar functionality. Do you have any suggestions on how to accomplish this with your plugins (or any other plugin you're aware of)?

**Comment by Colorado4Wheeler** [comment]
For now you can use Homebridge Buddy to accomplish it the way you did before, it will run along side HomeKit Bridge.  You don't need to enable or run the servers to use wrappers.

**Comment by Colorado4Wheeler** [comment]
There are plans to put this into Device Extensions but there is only so much time in the day to get all of this stuff done and I'm just running against a wall at the moment for time so no ETA on when this might be done.

**Comment by mrstacey1284** [comment]
I get it and appreciate everything you have put into all your plugins. I didn't realize I could run them both side by side. I'll take a look now. Thanks!
